/*
 * KeyCodes.h
 *
 * Created: 12/27/2014 3:30:38 PM
 *  Author: Jack
 */ 


#ifndef KEYCODES_H_
#define KEYCODES_H_

#define KEY_A HID_KEYBOARD_SC_A
#define KEY_Z HID_KEYBOARD_SC_Z

#define KEY_DASH HID_KEYBOARD_SC_MINUS_AND_UNDERSCORE
#define KEY_SLASH HID_KEYBOARD_SC_SLASH_AND_QUESTION_MARK

#define ASCII_0 48
#define ASCII_1 49
#define ASCII_9 57

#define KEY_1 HID_KEYBOARD_SC_1_AND_EXCLAMATION
#define KEY_2 HID_KEYBOARD_SC_2_AND_AT                          
#define KEY_3 HID_KEYBOARD_SC_3_AND_HASHMARK                    
#define KEY_4 HID_KEYBOARD_SC_4_AND_DOLLAR                      
#define KEY_5 HID_KEYBOARD_SC_5_AND_PERCENTAGE                  
#define KEY_6 HID_KEYBOARD_SC_6_AND_CARET                      
#define KEY_7 HID_KEYBOARD_SC_7_AND_AMPERSAND                   
#define KEY_8 HID_KEYBOARD_SC_8_AND_ASTERISK                    
#define KEY_9 HID_KEYBOARD_SC_9_AND_OPENING_PARENTHESIS         
#define KEY_0 HID_KEYBOARD_SC_0_AND_CLOSING_PARENTHESIS    

#define KEY_ENTER HID_KEYBOARD_SC_ENTER     
#define KEY_M HID_KEYBOARD_SC_M
#define KEY_SPACE HID_KEYBOARD_SC_SPACE
#define KEY_T HID_KEYBOARD_SC_T
#define KEY_U HID_KEYBOARD_SC_U
#define LOWER 0
#define UPPER HID_KEYBOARD_MODIFIER_LEFTSHIFT

#define KEY_PERIOD HID_KEYBOARD_SC_DOT_AND_GREATER_THAN_SIGN
#define KEY_COMMA HID_KEYBOARD_SC_COMMA_AND_LESS_THAN_SIGN
#define KEY_BACKSPACE HID_KEYBOARD_SC_BACKSPACE
#define KEY_DELETE  HID_KEYBOARD_SC_DELETE  
#define KEY_SLASH HID_KEYBOARD_SC_SLASH_AND_QUESTION_MARK
#define KEY_QUOTES HID_KEYBOARD_SC_APOSTROPHE_AND_QUOTE
#define KEY_ESC HID_KEYBOARD_SC_ESCAPE
#define KEY_TAB HID_KEYBOARD_SC_TAB   
#define KEY_EQ  HID_KEYBOARD_SC_EQUAL_AND_PLUS
#define KEY_DASH HID_KEYBOARD_SC_MINUS_AND_UNDERSCORE
#define KEY_BACKSLASH HID_KEYBOARD_SC_BACKSLASH_AND_PIPE
#define KEY_LBRACKET HID_KEYBOARD_SC_OPENING_BRACKET_AND_OPENING_BRACE
#define KEY_RBRACKET HID_KEYBOARD_SC_CLOSING_BRACKET_AND_CLOSING_BRACE
#define KEY_TILDE HID_KEYBOARD_SC_GRAVE_ACCENT_AND_TILDE 

#define KEY_F1 HID_KEYBOARD_SC_F1 

#define KEY_RIGHT HID_KEYBOARD_SC_RIGHT_ARROW 
#define  KEY_LEFT HID_KEYBOARD_SC_LEFT_ARROW 
#define KEY_DOWN HID_KEYBOARD_SC_DOWN_ARROW 
#define KEY_UP HID_KEYBOARD_SC_UP_ARROW 




#endif /* KEYCODES_H_ */